version: '3'

services:

  php:
    image: bitnami/php-fpm:latest
    container_name: php
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    restart: always

  database:
    build:
      context: .
      dockerfile: Dockerfile.bdd
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: cdp
      MYSQL_PORT_3306_TCP_ADDR: database
      MYSQL_PORT_3306_TCP_PORT: 3306
    ports:
      - 3306:3306

  web:
    build:
      context: .
    container_name: cdpphp
    ports:
      - 8100:80
    depends_on:
      - database
    links:
      - database
